version: "3.9"

services:
  api:
    build: ./judge
    ports:
      - "8080:8000"
    volumes:
      - problem_data:/data/problems
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:  # <--- AGREGA ESTO
      - .env

  worker:
    build: ./rekarel-worker
    volumes:
      - problem_data:/data/problems
    depends_on:
      - redis
    env_file:  # <--- AGREGA ESTO
      - .env

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: judge
      POSTGRES_USER: judge
      POSTGRES_PASSWORD: judge
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U judge -d judge"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5433:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  problem_data: