version: "3.9"

services:
  api:
    build: ./judge
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  worker:
    build: ./rekarel-worker
    depends_on:
      - redis

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: judge
      POSTGRES_USER: judge
      POSTGRES_PASSWORD: judge
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
